### ISSUE TITLE
Fails to build with g++ 4.8.2

### ISSUE THREAD

**Issue by certik** [bluescarni/piranha#6]
Here is the full build log for the commit 32b281fa8c9b41d5904613455a54a1c527764cdf:

https://gist.github.com/certik/d4f5e89d78ce45b09c84

Be sure to click on "view the full file".
The actual error is:

```
/projects/b1cc51a6-c4a2-4281-98b4-a5c2b1dea21b/.hashdist/tmp/piranha-xmzin5vuewji-4/tests/../src/polynomial.hpp:1437:8: error: 'boost::timer' has not been declared
 boost::timer::auto_cpu_timer t;
        ^
/projects/b1cc51a6-c4a2-4281-98b4-a5c2b1dea21b/.hashdist/tmp/piranha-xmzin5vuewji-4/tests/../src/polynomial.hpp:1437:30: error: expected ';' before 't'
 boost::timer::auto_cpu_timer t;
                              ^
```

The BOOST that I use is 1.55. There are lots of warnings, so the total log is over 6500 lines... I think this makes it really hard to see what's wrong. As an example, here is the log from csympy:

```
ondrej@kittiwake:~/repos/csympy(master)$     cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_CSYMPY_ASSERT=yes -DWITH_BFD=yes .
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++

-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found GMP: /nh/nest/u/ondrej/repos/hashstack/default/lib/libgmpxx.so;/nh/nest/u/ondrej/repos/hashstack/default/lib/libgmp.so  
-- Found BFD: /usr/lib/libbfd.so  
-- Found LINKH: /usr/include  


Configuration results
---------------------
C++ compiler: /usr/bin/c++
Build type: Debug
C++ compiler flags: -std=c++0x -Wall -Wextra -fPIC -g -Wno-unused-parameter -ggdb
Installation prefix: /usr/local
WITH_CSYMPY_ASSERT: yes
WITH_CSYMPY_RCP: yes
WITH_CSYMPY_THREAD_SAFE: no
GMP_INCLUDE_DIRS: /nh/nest/u/ondrej/repos/hashstack/default/include
GMP_LIBRARIES: /nh/nest/u/ondrej/repos/hashstack/default/lib/libgmpxx.so;/nh/nest/u/ondrej/repos/hashstack/default/lib/libgmp.so
WITH_BFD: yes
BFD_INCLUDE_DIRS: /usr/include
BFD_LIBRARIES: /usr/lib/libbfd.so
LINKH_INCLUDE_DIRS: /usr/include
WITH_PYTHON: no
WITH_ECM: no
WITH_PRIMESIEVE: no
Copying source of python wrappers into: /nh/nest/u/ondrej/repos/csympy
-- Configuring done
-- Generating done
-- Build files have been written to: /nh/nest/u/ondrej/repos/csympy
ondrej@kittiwake:~/repos/csympy(master)$ 
ondrej@kittiwake:~/repos/csympy(master)$ make
Scanning dependencies of target csympy
[  2%] Building CXX object src/CMakeFiles/csympy.dir/csympy_rcp.cpp.o
[  5%] Building CXX object src/CMakeFiles/csympy.dir/basic.cpp.o
[  7%] Building CXX object src/CMakeFiles/csympy.dir/dict.cpp.o
[ 10%] Building CXX object src/CMakeFiles/csympy.dir/symbol.cpp.o
[ 12%] Building CXX object src/CMakeFiles/csympy.dir/number.cpp.o
[ 15%] Building CXX object src/CMakeFiles/csympy.dir/integer.cpp.o
[ 17%] Building CXX object src/CMakeFiles/csympy.dir/rational.cpp.o
[ 20%] Building CXX object src/CMakeFiles/csympy.dir/add.cpp.o
[ 22%] Building CXX object src/CMakeFiles/csympy.dir/mul.cpp.o
[ 25%] Building CXX object src/CMakeFiles/csympy.dir/pow.cpp.o
[ 27%] Building CXX object src/CMakeFiles/csympy.dir/functions.cpp.o
[ 30%] Building CXX object src/CMakeFiles/csympy.dir/monomials.cpp.o
[ 32%] Building CXX object src/CMakeFiles/csympy.dir/rings.cpp.o
[ 35%] Building CXX object src/CMakeFiles/csympy.dir/ntheory.cpp.o
[ 37%] Building CXX object src/CMakeFiles/csympy.dir/dense_matrix.cpp.o
[ 40%] Building CXX object src/CMakeFiles/csympy.dir/sparse_matrix.cpp.o
Linking CXX static library libcsympy.a
[ 40%] Built target csympy
Scanning dependencies of target teuchos
[ 42%] Building CXX object src/teuchos/CMakeFiles/teuchos.dir/Teuchos_dyn_cast.cpp.o
[ 45%] Building CXX object src/teuchos/CMakeFiles/teuchos.dir/Teuchos_Ptr.cpp.o
[ 47%] Building CXX object src/teuchos/CMakeFiles/teuchos.dir/Teuchos_RCPNode.cpp.o
[ 50%] Building CXX object src/teuchos/CMakeFiles/teuchos.dir/Teuchos_TestForException.cpp.o
[ 52%] Building CXX object src/teuchos/CMakeFiles/teuchos.dir/Teuchos_TypeNameTraits.cpp.o
[ 55%] Building CXX object src/teuchos/CMakeFiles/teuchos.dir/Teuchos_stacktrace.cpp.o
Linking CXX static library libteuchos.a
[ 55%] Built target teuchos
Scanning dependencies of target test_rcp
[ 57%] Building CXX object src/tests/rcp/CMakeFiles/test_rcp.dir/test_rcp.cpp.o
Linking CXX executable test_rcp
[ 57%] Built target test_rcp
Scanning dependencies of target test_arit
[ 60%] Building CXX object src/tests/basic/CMakeFiles/test_arit.dir/test_arit.cpp.o
Linking CXX executable test_arit
[ 60%] Built target test_arit
Scanning dependencies of target test_basic
[ 62%] Building CXX object src/tests/basic/CMakeFiles/test_basic.dir/test_basic.cpp.o
Linking CXX executable test_basic
[ 62%] Built target test_basic
Scanning dependencies of target test_functions
[ 65%] Building CXX object src/tests/basic/CMakeFiles/test_functions.dir/test_functions.cpp.o
Linking CXX executable test_functions
[ 65%] Built target test_functions
Scanning dependencies of target test_integer
[ 67%] Building CXX object src/tests/basic/CMakeFiles/test_integer.dir/test_integer.cpp.o
Linking CXX executable test_integer
[ 67%] Built target test_integer
Scanning dependencies of target test_poly
[ 70%] Building CXX object src/tests/basic/CMakeFiles/test_poly.dir/test_poly.cpp.o
Linking CXX executable test_poly
[ 70%] Built target test_poly
Scanning dependencies of target test_subs
[ 72%] Building CXX object src/tests/basic/CMakeFiles/test_subs.dir/test_subs.cpp.o
Linking CXX executable test_subs
[ 72%] Built target test_subs
Scanning dependencies of target test_ntheory
[ 75%] Building CXX object src/tests/ntheory/CMakeFiles/test_ntheory.dir/test_ntheory.cpp.o
Linking CXX executable test_ntheory
[ 75%] Built target test_ntheory
Scanning dependencies of target test_matrix
[ 77%] Building CXX object src/tests/matrix/CMakeFiles/test_matrix.dir/test_matrix.cpp.o
Linking CXX executable test_matrix
[ 77%] Built target test_matrix
Scanning dependencies of target test_printing
[ 80%] Building CXX object src/tests/printing/CMakeFiles/test_printing.dir/test_printing.cpp.o
Linking CXX executable test_printing
[ 80%] Built target test_printing
Scanning dependencies of target expand1
[ 82%] Building CXX object benchmarks/CMakeFiles/expand1.dir/expand1.cpp.o
Linking CXX executable expand1
[ 82%] Built target expand1
Scanning dependencies of target expand2
[ 85%] Building CXX object benchmarks/CMakeFiles/expand2.dir/expand2.cpp.o
Linking CXX executable expand2
[ 85%] Built target expand2
Scanning dependencies of target expand2b
[ 87%] Building CXX object benchmarks/CMakeFiles/expand2b.dir/expand2b.cpp.o
Linking CXX executable expand2b
[ 87%] Built target expand2b
Scanning dependencies of target expand3
[ 90%] Building CXX object benchmarks/CMakeFiles/expand3.dir/expand3.cpp.o
Linking CXX executable expand3
[ 90%] Built target expand3
Scanning dependencies of target matrix_add1
[ 92%] Building CXX object benchmarks/CMakeFiles/matrix_add1.dir/matrix_add1.cpp.o
Linking CXX executable matrix_add1
[ 92%] Built target matrix_add1
Scanning dependencies of target matrix_add2
[ 95%] Building CXX object benchmarks/CMakeFiles/matrix_add2.dir/matrix_add2.cpp.o
Linking CXX executable matrix_add2
[ 95%] Built target matrix_add2
Scanning dependencies of target matrix_mul1
[ 97%] Building CXX object benchmarks/CMakeFiles/matrix_mul1.dir/matrix_mul1.cpp.o
Linking CXX executable matrix_mul1
[ 97%] Built target matrix_mul1
Scanning dependencies of target matrix_mul2
[100%] Building CXX object benchmarks/CMakeFiles/matrix_mul2.dir/matrix_mul2.cpp.o
Linking CXX executable matrix_mul2
[100%] Built target matrix_mul2
```

I.e. no warnings at all.
